project_id = "jbvepseodqytqxxckgtu"

[functions.admin-leads]
verify_jwt = false

[functions.marketing-optin]
verify_jwt = false

[functions.admin-optin]
verify_jwt = false

[functions.optin-sync-worker]
verify_jwt = false

