// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista leads de triagem (formul\xE1rio /1contato) filtrados por status do funil. Requer usu\xE1rio admin.",
  inputSchema: {
    status: z.enum(["new", "contacted", "booked", "won", "lost"]).optional().describe("Filtrar por status do funil."),
    limit: z.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("triagem_leads").select("id, nome, telefone, email, servico, categoria, status_funil, created_at, utm_source").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status_funil", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Detalhar lead",
  description: "Retorna todos os campos de um lead de triagem pelo id. Requer admin.",
  inputSchema: {
    id: z2.string().uuid().describe("UUID do lead.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("triagem_leads").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Lead n\xE3o encontrado." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/update-lead-status.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_lead_status_default = defineTool3({
  name: "update_lead_status",
  title: "Atualizar status do lead",
  description: "Atualiza o status do funil de um lead (new, contacted, booked, won, lost). Requer admin.",
  inputSchema: {
    id: z3.string().uuid(),
    status_funil: z3.enum(["new", "contacted", "booked", "won", "lost"])
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ id, status_funil }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("triagem_leads").update({ status_funil, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", id).select("id, status_funil").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Lead n\xE3o encontrado ou sem permiss\xE3o." }], isError: true };
    return {
      content: [{ type: "text", text: `Lead ${data.id} atualizado para ${data.status_funil}.` }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jbvepseodqytqxxckgtu";
var mcp_default = defineMcp({
  name: "aptos-autoescola-mcp",
  title: "Autoescola APTOS",
  version: "0.1.0",
  instructions: "Ferramentas para consultar e gerenciar leads da triagem (/1contato) da Autoescola APTOS. Requer login como administrador.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, update_lead_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
